name: Sync Upstream

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

env:
  UPSTREAM_URL: "https://github.com/j-hc/revanced-magisk-module.git"
  WORKFLOW_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
  UPSTREAM_BRANCH: "main"
  DOWNSTREAM_BRANCH: "main"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync Upstream
        uses: tanishqmanuja/sync-upstream-repo@v1.0.0
        with:
          upstream_repo: ${{ env.UPSTREAM_URL }}
          upstream_branch: ${{ env.UPSTREAM_BRANCH }}
          downstream_branch: ${{ env.DOWNSTREAM_BRANCH }}
          token: ${{ env.WORKFLOW_TOKEN }}
          git_config_args: |
            merge.ours.name 'Keep ours during merge'
            merge.ours.driver true
